package plasystem_functions;

import javax.swing.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 * Utility class for generating transaction reports in CSV format for the PlaSystem application.
 * The report includes transaction details and their associated items, saved to a timestamped
 * file in the "transaction_reports" directory.
 */
public class TransactionReportGenerator {
    /** Directory path where transaction reports are saved. */
    private static final String REPORTS_DIRECTORY = "transaction_reports";
    
    /** List of transactions to include in the report. */
    private final List<TransactionData> transactionList;
    
    /** Column headers for the CSV report, combining transaction and item details. */
    private static final String[] COMBINED_HEADERS = {
        "Transaction ID", "Date", "Time", "Total Amount", "Payment Amount", "Change Amount",
        "Product Name", "Brand", "Size", "Type", "Buy Quantity", "Unit Price", "Total Price"
    };

    /**
     * Constructs a TransactionReportGenerator with the specified list of transactions.
     *
     * @param transactionList The list of transactions to include in the report. Must not be null.
     * @throws NullPointerException if transactionList is null.
     */
    public TransactionReportGenerator(List<TransactionData> transactionList) {
        this.transactionList = transactionList;
    }

    /**
     * Generates a CSV transaction report after prompting the user for confirmation. If confirmed,
     * the report is saved in the "transaction_reports" directory with a timestamped filename
     * (e.g., TransactionReport_YYYY-MM-DD_HHMMSS.csv). Displays a success or error message to the user.
     *
     * @param parent The parent JFrame for displaying confirmation and result dialogs. May be null
     *               if no parent is required.
     */
    public void generateReport(JFrame parent) {
        // Prompt user to confirm export
        int choice = JOptionPane.showConfirmDialog(
            parent,
            "Do you want to export the transaction report as a CSV file?",
            "Export Transaction Report",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (choice != JOptionPane.YES_OPTION) {
            return; // User cancelled or selected No
        }

        // Create transaction_reports directory if it doesn't exist
        File reportsDir = new File(REPORTS_DIRECTORY);
        if (!reportsDir.exists()) {
            reportsDir.mkdirs();
        }

        // Generate filename with specific format: TransactionReport_YYYY-MM-DD_HHMMSS
        String timestamp = new SimpleDateFormat("yyyy-MM-dd_HHmmss").format(new Date());
        String filePath = REPORTS_DIRECTORY + "/TransactionReport_" + timestamp + ".csv";

        try {
            generateCSVReport(filePath);
            JOptionPane.showMessageDialog(parent,
                "Report generated successfully at: " + filePath,
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(parent,
                "Error generating report: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Generates a CSV report containing transaction data and their associated items in a
     * flattened format. Each row represents a transaction item with its transaction details.
     * Includes a header with metadata and column names.
     *
     * @param filePath The path where the CSV file will be saved. Must not be null or empty.
     * @throws IOException If an error occurs during file writing, such as insufficient permissions
     *                     or disk space issues.
     * @throws NullPointerException If filePath is null or if transactionList or any transaction
     *                              item's attributes are null.
     */
    private void generateCSVReport(String filePath) throws IOException {
        try (FileWriter writer = new FileWriter(filePath)) {
            // Write header
            writer.write("Transaction Report\n");
            writer.write("Generated by PlaSystem\n");
            writer.write("Total Different Transactions: " + transactionList.size() + "\n\n");

            // Write combined headers
            writer.write(String.join(",", COMBINED_HEADERS) + "\n");

            // Write data rows
            for (TransactionData transaction : transactionList) {
                // For each transaction, write a row for each of its items
                for (TransactionItemData item : transaction.getTransactionItems()) {
                    String[] row = {
                        String.valueOf(transaction.getTransactionId()),
                        transaction.getFormattedDate().split(" ")[0], // YYYY-MM-DD
                        transaction.getTransDateTime(),
                        String.valueOf(transaction.getTotalAmount()),
                        String.valueOf(transaction.getPaymentAmount()),
                        String.valueOf(transaction.getChangeAmount()),
                        item.getTI_productName(),
                        item.getTI_productBrand(),
                        item.getTI_productSize(),
                        item.getTI_productType(),
                        String.valueOf(item.getTI_buyQuantity()),
                        String.valueOf(item.getTI_unitPrice()),
                        String.valueOf(item.getTI_totalPrice())
                    };
                    writer.write(String.join(",", row) + "\n");
                }
            }
        }
    }
}