package plasystem_gui;

import plasystem_functions.UserAccountDataManager;
import javax.swing.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

public class LaunchPanelGUI extends javax.swing.JFrame {
    
    private final UserAccountDataManager userAccountDataModel;
    
    public LaunchPanelGUI() {
        initComponents(); // Initialize GUI components
        setLocationRelativeTo(null); // Set the location of the frame to the center of the screen
        
        // Initialize the UserAccountDataManager and load user accounts
        userAccountDataModel = new UserAccountDataManager();
        
        // Add KeyListeners for Enter key action
        addEnterKeyListener(usernameTxtField);
        addEnterKeyListener(passwordTxtField);
    }
    
    private void addEnterKeyListener(JTextField textField) {
        textField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    launchBtnActionPerformed(null); // Simulate button click when Enter is pressed
                }
            }
        });
    }
    
    private void launchMainProgram() {
        JFrame mainProgram = new MainProgramGUI(userAccountDataModel); // Pass UserAccountDataManager
        mainProgram.setVisible(true); // Set the main program frame visible
        mainProgram.pack();
        mainProgram.setLocationRelativeTo(null);
        this.dispose(); // Dispose of the current frame (LaunchPanelGUI)
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        launchPanel = new javax.swing.JPanel();
        passwordTxtField = new javax.swing.JPasswordField();
        versionTxTField = new javax.swing.JLabel();
        launchBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        usernameTxtField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        backgroundDesign = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        passwordTxtField.setText("tjb123");

        versionTxTField.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        versionTxTField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionTxTField.setText("version 3.0.0");

        launchBtn.setBackground(new java.awt.Color(0, 153, 255));
        launchBtn.setForeground(new java.awt.Color(255, 255, 255));
        launchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plasystem_resources/launchbtn_icon.png"))); // NOI18N
        launchBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        launchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchBtnActionPerformed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 102, 102));
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plasystem_resources/exitbtn_icon.png"))); // NOI18N
        exitBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitBtn.setInheritsPopupMenu(true);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordLabel.setText(" Password :");

        usernameTxtField.setText("admin");

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usernameLabel.setText("Username :");

        backgroundDesign.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backgroundDesign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plasystem_resources/launchpanel_mainmenu.gif"))); // NOI18N

        javax.swing.GroupLayout launchPanelLayout = new javax.swing.GroupLayout(launchPanel);
        launchPanel.setLayout(launchPanelLayout);
        launchPanelLayout.setHorizontalGroup(
            launchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(launchPanelLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(launchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usernameLabel)
                    .addComponent(passwordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(launchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameTxtField)
                    .addComponent(passwordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(launchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, launchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(versionTxTField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(456, 456, 456))
            .addGroup(launchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(backgroundDesign, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1089, Short.MAX_VALUE))
        );
        launchPanelLayout.setVerticalGroup(
            launchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(launchPanelLayout.createSequentialGroup()
                .addContainerGap(374, Short.MAX_VALUE)
                .addGroup(launchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, launchPanelLayout.createSequentialGroup()
                        .addGroup(launchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(launchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel))
                        .addGap(49, 49, 49)
                        .addComponent(versionTxTField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, launchPanelLayout.createSequentialGroup()
                        .addComponent(launchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, launchPanelLayout.createSequentialGroup()
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))))
            .addGroup(launchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(launchPanelLayout.createSequentialGroup()
                    .addComponent(backgroundDesign)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(launchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(launchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void launchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchBtnActionPerformed
        String username = usernameTxtField.getText().trim();
        String password = new String(passwordTxtField.getPassword()).trim();

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both username and password.");
            return;
        }

        if (userAccountDataModel.validateUserLogin(username, password)) {
            launchMainProgram();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password.");
        }
    }//GEN-LAST:event_launchBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0); // Close the application
    }//GEN-LAST:event_exitBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundDesign;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton launchBtn;
    private javax.swing.JPanel launchPanel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTxtField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTxtField;
    private javax.swing.JLabel versionTxTField;
    // End of variables declaration//GEN-END:variables
}
