package plasystem_gui;

import plasystem_functions.*;
import javax.swing.*;
import javax.swing.table.*;
import java.text.DecimalFormat;

public class RHDetailsGUI extends javax.swing.JFrame {
    private final RestockData restock;

    /**
     * Default constructor initializing the RHDetailsGUI.
     */
    public RHDetailsGUI() {
        this.restock = null;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * Creates new form RHDetailsGUI with restock data.
     *
     * @param restock The restock whose items are to be displayed.
     */
    public RHDetailsGUI(RestockData restock) {
        this.restock = restock;
        initComponents();
        setLocationRelativeTo(null);
        new PriceTableRenderer(rhDetailsTbl);
        updateTable();
    }
    
    /**
     * Updates the table with restock items.
     */
    private void updateTable() {
        if (restock == null || restock.getRestockItems() == null) {
            return;
        }

        DefaultTableModel rhTblModel = (DefaultTableModel) rhDetailsTbl.getModel();
        rhTblModel.setRowCount(0); // Clear existing rows

        for (RestockItemData rhItem : restock.getRestockItems()) {
            rhTblModel.addRow(new Object[]{
                rhItem.getRI_productName(),
                rhItem.getRI_productBrand(),
                rhItem.getRI_productSize(),
                rhItem.getRI_productType(),
                rhItem.getRI_productPrice(),
                rhItem.getRI_restockedQuantity()
            });
        }
    }
    
    /**
     * Custom renderer to format and align price columns.
     */
    private static class PriceTableRenderer {
        private final JTable table;

        public PriceTableRenderer(JTable table) {
            this.table = table;
            applyPriceFormattingAndAlignment();
        }

        /**
         * Applies decimal formatting and right alignment to the price column.
         */
        private void applyPriceFormattingAndAlignment() {
            DecimalFormatRenderer renderer = new DecimalFormatRenderer();
            renderer.setHorizontalAlignment(SwingConstants.RIGHT);
            TableColumnModel columnModel = table.getColumnModel();
            // Apply to Price (index 4)
            columnModel.getColumn(4).setCellRenderer(renderer);
        }

        /**
         * Inner renderer to format double values to two decimal places.
         */
        private static class DecimalFormatRenderer extends DefaultTableCellRenderer {
            private final DecimalFormat formatter = new DecimalFormat("#0.00");

            @Override
            public java.awt.Component getTableCellRendererComponent(JTable table, Object value,
                                                                   boolean isSelected, boolean hasFocus,
                                                                   int row, int column) {
                if (value instanceof Number) {
                    value = formatter.format(((Number) value).doubleValue());
                }
                return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rhDetailsScrollPane = new javax.swing.JScrollPane();
        rhDetailsTbl = new javax.swing.JTable();
        design1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        rhDetailsTbl.setAutoCreateRowSorter(true);
        rhDetailsTbl.getTableHeader().setReorderingAllowed(false);
        rhDetailsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Brand", "Size", "Type", "Price", "Restocked Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rhDetailsScrollPane.setViewportView(rhDetailsTbl);

        design1.setBackground(new java.awt.Color(153, 204, 0));
        design1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        design1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plasystem_resources/rhdetails_title.png"))); // NOI18N
        design1.setToolTipText("");
        design1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rhDetailsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(design1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(rhDetailsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(design1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, Short.MAX_VALUE)
                    .addGap(274, 274, 274)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel design1;
    private javax.swing.JScrollPane rhDetailsScrollPane;
    private javax.swing.JTable rhDetailsTbl;
    // End of variables declaration//GEN-END:variables
}
