package plasystem_gui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import plasystem_functions.*;
import javax.swing.*;
import javax.swing.table.*;
import java.util.*;
import java.util.function.Supplier;

public class TransactionHistoryGUI extends javax.swing.JFrame {
    private TransactionDataManager transactionDataModel;
    private List<TransactionData> transactionList;
        // List to track open child GUIs
    private final List<JFrame> childGUIs = new ArrayList<>();
    // Map to track instances of active GUIs
    private final Map<Class<? extends JFrame>, JFrame> activeGUIs = new HashMap<>();
    
    /**
     * Default constructor initializing the TransactionHistoryGUI.
     */
    public TransactionHistoryGUI() {
        initComponents();
        setLocationRelativeTo(null); // Set the frame to appear in the center of the screen
    }
    
    /**
     * Constructor initializing the Transaction History GUI with a provided TransactionDataManager.
     *
     * @param transactionDataManager The TransactionDataManager instance to use for database operations.
     */
    public TransactionHistoryGUI(TransactionDataManager transactionDataManager) {
        this.transactionDataModel = transactionDataManager;
        this.transactionList = transactionDataManager.getTransactionList();
        initComponents();
        setLocationRelativeTo(null);
        updateTable();
        new TransactionHistoryTableRenderer(transHistorytbl, 667); // 667 is the table width
    }
    
    // Method to add a child GUI to the tracking list
    public void addChildGUI(JFrame child) {
        childGUIs.add(child);
    }

    // Method to remove a child GUI from the tracking list
    public void removeChildGUI(JFrame child) {
        childGUIs.remove(child);
    }
    
    /**
     * Launches or focuses a single instance of a GUI.
     *
     * @param guiClass The class of the GUI to launch.
     * @param creator  A lambda to create a new instance of the GUI if needed.
     * @return The GUI instance.
     */
    private <T extends JFrame> T launchSingleInstance(Class<T> guiClass, Supplier<T> creator) {
        JFrame existingInstance = activeGUIs.get(guiClass);
        if (existingInstance != null && !existingInstance.isDisplayable()) {
            activeGUIs.remove(guiClass); // Remove disposed instance
            existingInstance = null;
        }

        if (existingInstance != null) {
            JOptionPane.showMessageDialog(
                existingInstance,
                "Only one instance can be present.",
                "Instance Warning",
                JOptionPane.WARNING_MESSAGE
            );
            existingInstance.requestFocus();
            existingInstance.setVisible(true);
            return guiClass.cast(existingInstance);
        }

        T newInstance = creator.get();
        newInstance.setVisible(true);
        newInstance.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        newInstance.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                activeGUIs.remove(guiClass);
                removeChildGUI(newInstance);
            }
        });
        activeGUIs.put(guiClass, newInstance);
        addChildGUI(newInstance);
        return newInstance;
    }
    
    // Override dispose to close all child windows
    @Override
    public void dispose() {
        // Close all child windows
        for (JFrame child : new ArrayList<>(childGUIs)) {
            child.dispose();
        }
        childGUIs.clear(); // Clear the list
        super.dispose(); // Call parent dispose
    }
    
    /**
     * Updates the transaction history table with data from the database.
     */
    private void updateTable() {
        DefaultTableModel transHistoryTblModel = (DefaultTableModel) transHistorytbl.getModel();
        transHistoryTblModel.setRowCount(0); // Clear existing rows

        for (TransactionData transaction : transactionList) {
            transHistoryTblModel.addRow(new Object[]{
                transaction.getTransactionId(),
                transaction.getFormattedDate().split(" ")[0], // Date (YYYY-MM-DD)
                transaction.getTransDateTime(), // Time
                transaction.getTotalAmount(),
                transaction.getPaymentAmount(),
                transaction.getChangeAmount()
            });
        }
        
        // Reapply search filter if active
        if (!searchTxtField.getText().trim().isEmpty()) {
            searchTxtFieldKeyReleased(null);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transHistoryScrollPane = new javax.swing.JScrollPane();
        transHistorytbl = new javax.swing.JTable();
        detailsBtn = new javax.swing.JButton();
        searchTxtField = new javax.swing.JTextField();
        searchPrmtrBox = new javax.swing.JComboBox<>();
        design1 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        exportBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        setResizable(false);

        transHistorytbl.setAutoCreateRowSorter(true);
        transHistorytbl.getTableHeader().setReorderingAllowed(false);
        transHistorytbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Time", "Total Amount", "Payment Amount", "Change Given"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transHistoryScrollPane.setViewportView(transHistorytbl);

        detailsBtn.setText("See Details");
        detailsBtn.setInheritsPopupMenu(true);
        detailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsBtnActionPerformed(evt);
            }
        });

        searchTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtFieldKeyReleased(evt);
            }
        });

        searchPrmtrBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Year", "Month", "Day", "Date", "Total Amount", "Payment Amount", "Change Given" }));

        design1.setBackground(new java.awt.Color(255, 102, 102));
        design1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        design1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plasystem_resources/transact_history_title.png"))); // NOI18N
        design1.setOpaque(true);

        deleteBtn.setBackground(new java.awt.Color(255, 102, 102));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.setInheritsPopupMenu(true);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        exportBtn.setText("🖨️ Export");
        exportBtn.setInheritsPopupMenu(true);
        exportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(design1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transHistoryScrollPane)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchPrmtrBox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195)
                        .addComponent(refreshBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(467, 467, 467)
                        .addComponent(detailsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(design1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchTxtField)
                            .addComponent(searchPrmtrBox)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(refreshBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(3, 3, 3)
                .addComponent(transHistoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(exportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Handles the "See Details" button click, displaying transaction items for the selected transaction.
     */
    private void detailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsBtnActionPerformed
        int selectedRow = transHistorytbl.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a transaction to view details.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convert view index to transHistoryTblModel index to account for sorting/filtering
        selectedRow = transHistorytbl.convertRowIndexToModel(selectedRow);
        int transactionId = (int) transHistorytbl.getModel().getValueAt(selectedRow, 0);
        TransactionData selectedTransaction = transactionList.stream()
            .filter(t -> t.getTransactionId() == transactionId)
            .findFirst()
            .orElse(null);

        if (selectedTransaction != null) {
            launchSingleInstance(THDetailsGUI.class, () -> {
                THDetailsGUI thDetailGUI = new THDetailsGUI(selectedTransaction);
                thDetailGUI.pack();
                thDetailGUI.setLocationRelativeTo(null);
                thDetailGUI.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                return thDetailGUI;
            });
        } else {
            JOptionPane.showMessageDialog(this, "Transaction not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_detailsBtnActionPerformed
    
    /**
     * Handles the "Delete" button click, removing the selected transaction using TransactionDataManager.
     */
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int selectedRow = transHistorytbl.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a transaction to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convert view index to transHistoryTblModel index
        selectedRow = transHistorytbl.convertRowIndexToModel(selectedRow);
        int transactionId = (int) transHistorytbl.getModel().getValueAt(selectedRow, 0);

        int confirmDelete = JOptionPane.showConfirmDialog(this,
            "Do you really want to delete transaction ID " + transactionId + "?",
            "Delete",
            JOptionPane.YES_NO_OPTION);
        if (confirmDelete == JOptionPane.YES_OPTION) {
            boolean success = transactionDataModel.deleteTransaction(transactionId);
            if (success) {
                updateTable();
                JOptionPane.showMessageDialog(this, "Transaction deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete transaction.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed
    
    /**
     * Handles the "Refresh" button click, reloading the table with the latest transactions.
     */
    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        updateTable();
    }//GEN-LAST:event_refreshBtnActionPerformed
    
    /**
     * Handles search functionality, filtering the table based on the search text and parameter.
     */
    private void searchTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtFieldKeyReleased
        DefaultTableModel transHistoryTblModel = (DefaultTableModel) transHistorytbl.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(transHistoryTblModel);
        transHistorytbl.setRowSorter(sorter);

        String searchText = searchTxtField.getText().trim();
        String param = searchPrmtrBox.getSelectedItem().toString();

        if (searchText.isEmpty()) {
            sorter.setRowFilter(null);
            return;
        }

        // Handle month name to numeric conversion for Month parameter
        String filterText = param.equals("Month") ? MonthConverter.monthNameToNumeric(searchText) : searchText;

        // Map parameter to column index using switch expression
        int columnIndex = switch (param) {
            case "ID" -> 0;
            case "Date", "Year", "Month", "Day" -> 1; // Date column
            case "Total Amount" -> 3;
            case "Payment Amount" -> 4;
            case "Change Given" -> 5;
            default -> throw new IllegalArgumentException("Invalid search parameter: " + param);
        };

        // Apply case-insensitive regex filter using switch expression
        try {
            RowFilter<DefaultTableModel, Object> filter = switch (param) {
                case "Date" -> RowFilter.regexFilter("(?i)" + searchTxtField.getText(), columnIndex);
                case "Year" -> RowFilter.regexFilter("(?i)^" + filterText + "-.*", columnIndex);
                case "Month" -> RowFilter.regexFilter("(?i)^\\d{4}-" + filterText + "-.*", columnIndex);
                case "Day" -> RowFilter.regexFilter("(?i)^\\d{4}-\\d{2}-" + filterText + ".*", columnIndex);
                default -> RowFilter.regexFilter("(?i)" + filterText, columnIndex);
            };
            sorter.setRowFilter(filter);
        } catch (Exception e) {
            sorter.setRowFilter(null);
        }
    }//GEN-LAST:event_searchTxtFieldKeyReleased

    private void exportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBtnActionPerformed
        TransactionReportGenerator reportGenerator = new TransactionReportGenerator(transactionList);
        reportGenerator.generateReport(this);
    }//GEN-LAST:event_exportBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel design1;
    private javax.swing.JButton detailsBtn;
    private javax.swing.JButton exportBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JComboBox<String> searchPrmtrBox;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JScrollPane transHistoryScrollPane;
    private javax.swing.JTable transHistorytbl;
    // End of variables declaration//GEN-END:variables
}