package datamine_gui;

import datamine_functions.*;
import java.util.*;
import javax.swing.*;
import javax.swing.event.*;
import java.awt.*;
import java.awt.event.*;
import java.time.*;
import javax.swing.table.*;

/**
 * Represents a GUI for handling transactions.
 */
public class TransactionGUI extends JFrame {
    // Attributes for handling data
    private LinkedList<GameData> list;
    TransactionHandling handling = new TransactionHandling();
    ErrorValueHandling isDataValid = new ErrorValueHandling();
    RandomIDGenerator receiptID = new RandomIDGenerator();
    private LinkedList<TransactionHandling> transactionList = new LinkedList<>();
    private int quantityChecker;
    private String path;
    private JTable tableData;
    private Double customerMoney;
    private Double totalPurchase;
    
    /**
     * Default constructor for the EditDataGUI.
     */
    public TransactionGUI(){
        initComponents(); // Initialize GUI components
        setLocationRelativeTo(null); // Set the frame's location to the center of the screen
    }
    
    /**
     * Creates a new instance of TransactionGUI with specific parameters.
     *
     * @param list      The list of GameData for transaction handling.
     * @param path      The path for file handling.
     * @param tableData The JTable for displaying transaction data.
     */    
    public TransactionGUI(LinkedList<GameData> list,String path, JTable tableData){
        initComponents(); // Initialize GUI components
        setLocationRelativeTo(null); // Set the frame's location to the center of the screen
        this.list = list; // Set the GameData list
        this.path = path; // Set the file path
        this.tableData = tableData; // Set the JTable for transaction data
        dateTxtField.setText(LocalDate.now().toString()); // Set the current date
        
        // Disable certain buttons and textfields initially
        addBtn.setEnabled(false);
        totalAmountTxtField.setEnabled(false);
        prodNameTxtField.setEnabled(false);
        itemPriceTxtField.setEnabled(false);
        dateTxtField.setEnabled(false);
        transactionTable.setEnabled(false);
        printReceiptBtn.setEnabled(false);
        
        // Add a change listener to ensure quantityPicker accepts only non-negative values
        quantityPicker.addChangeListener((ChangeEvent e) -> {
            int value = (int) quantityPicker.getValue();
            if (value < 0) {
                quantityPicker.setValue(0); // Set the value to 0 if it's negative
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transactPanel = new JPanel();
        prodIDLabel = new JLabel();
        itemPriceLabel = new JLabel();
        paymentAmountLabel = new JLabel();
        itemPriceTxtField = new JTextField();
        prodIDTxtField = new JTextField();
        dateTxtField = new JTextField();
        dateLabel = new JLabel();
        verifyBtn = new JButton();
        totalAmountLabel = new JLabel();
        totalAmountTxtField = new JTextField();
        paymentAmountTxtField = new JTextField();
        quantityLabel = new JLabel();
        quantityPicker = new JSpinner();
        addBtn = new JButton();
        prodNameLabel = new JLabel();
        prodNameTxtField = new JTextField();
        clearBtn = new JButton();
        jScrollPane2 = new JScrollPane();
        transactionTable = new JTable();
        titleLabel = new JLabel();
        cancelBtn = new JButton();
        printReceiptBtn = new JButton();
        submitBtn = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        transactPanel.setBorder(BorderFactory.createTitledBorder(""));

        prodIDLabel.setFont(new Font("Segoe UI", 0, 13)); // NOI18N
        prodIDLabel.setText("Product ID:");

        itemPriceLabel.setFont(new Font("Segoe UI", 0, 13)); // NOI18N
        itemPriceLabel.setText("Item Price:");

        paymentAmountLabel.setFont(new Font("Segoe UI", 0, 13)); // NOI18N
        paymentAmountLabel.setText("Payment Amount:");

        itemPriceTxtField.setEditable(false);

        dateTxtField.setEditable(false);

        dateLabel.setFont(new Font("Segoe UI", 0, 13)); // NOI18N
        dateLabel.setText("Date of Transaction:");

        verifyBtn.setBackground(new Color(102, 102, 102));
        verifyBtn.setFont(new Font("Segoe UI Semibold", 0, 13)); // NOI18N
        verifyBtn.setText("VERIFY PRODUCT");
        verifyBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                verifyBtnActionPerformed(evt);
            }
        });

        totalAmountLabel.setFont(new Font("Segoe UI", 0, 13)); // NOI18N
        totalAmountLabel.setText("Total:");

        totalAmountTxtField.setEditable(false);

        quantityLabel.setFont(new Font("Segoe UI", 0, 13)); // NOI18N
        quantityLabel.setText("Quantity:");

        addBtn.setBackground(new Color(102, 102, 102));
        addBtn.setFont(new Font("Segoe UI Semibold", 0, 13)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        prodNameLabel.setText("Product Name:");

        prodNameTxtField.setEditable(false);

        clearBtn.setBackground(new Color(102, 102, 102));
        clearBtn.setFont(new Font("Segoe UI Semibold", 0, 13)); // NOI18N
        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        transactionTable.setFont(new Font("Lucida Sans Typewriter", 0, 10)); // NOI18N
        transactionTable.setForeground(new Color(255, 102, 51));
        transactionTable.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "QUANTITY", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transactionTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(transactionTable);
        if (transactionTable.getColumnModel().getColumnCount() > 0) {
            transactionTable.getColumnModel().getColumn(1).setPreferredWidth(20);
            transactionTable.getColumnModel().getColumn(2).setPreferredWidth(25);
        }

        GroupLayout transactPanelLayout = new GroupLayout(transactPanel);
        transactPanel.setLayout(transactPanelLayout);
        transactPanelLayout.setHorizontalGroup(
            transactPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(transactPanelLayout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(transactPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addGroup(transactPanelLayout.createSequentialGroup()
                        .addComponent(paymentAmountLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paymentAmountTxtField, GroupLayout.PREFERRED_SIZE, 214, GroupLayout.PREFERRED_SIZE))
                    .addGroup(GroupLayout.Alignment.LEADING, transactPanelLayout.createSequentialGroup()
                        .addComponent(verifyBtn, GroupLayout.PREFERRED_SIZE, 139, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addBtn, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(clearBtn, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE))
                    .addGroup(transactPanelLayout.createSequentialGroup()
                        .addGroup(transactPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(prodNameLabel)
                            .addComponent(itemPriceLabel)
                            .addComponent(quantityLabel)
                            .addComponent(prodIDLabel))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(transactPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(itemPriceTxtField)
                            .addComponent(prodNameTxtField, GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(prodIDTxtField)
                            .addComponent(quantityPicker, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(transactPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(transactPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(totalAmountLabel)
                        .addGap(18, 18, 18)
                        .addComponent(totalAmountTxtField, GroupLayout.PREFERRED_SIZE, 214, GroupLayout.PREFERRED_SIZE))
                    .addGroup(transactPanelLayout.createSequentialGroup()
                        .addComponent(dateLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateTxtField, GroupLayout.PREFERRED_SIZE, 214, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        transactPanelLayout.setVerticalGroup(
            transactPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(transactPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(transactPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(prodIDLabel)
                    .addComponent(prodIDTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel)
                    .addComponent(dateTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(transactPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(transactPanelLayout.createSequentialGroup()
                        .addGroup(transactPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(prodNameTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodNameLabel))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transactPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(itemPriceLabel)
                            .addComponent(itemPriceTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transactPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(quantityLabel)
                            .addComponent(quantityPicker, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(transactPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentAmountLabel)
                            .addComponent(paymentAmountTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(transactPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(verifyBtn, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearBtn, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(transactPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(totalAmountLabel)
                    .addComponent(totalAmountTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titleLabel.setFont(new Font("Segoe UI Semibold", 0, 15)); // NOI18N
        titleLabel.setText(" DataMine Transaction");

        cancelBtn.setBackground(new Color(102, 102, 102));
        cancelBtn.setFont(new Font("Segoe UI Semibold", 0, 13)); // NOI18N
        cancelBtn.setText("CANCEL");
        cancelBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        printReceiptBtn.setBackground(new Color(102, 102, 102));
        printReceiptBtn.setFont(new Font("Segoe UI Semibold", 0, 13)); // NOI18N
        printReceiptBtn.setText("PRINT RECEIPT");
        printReceiptBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                printReceiptBtnActionPerformed(evt);
            }
        });

        submitBtn.setBackground(new Color(102, 102, 102));
        submitBtn.setFont(new Font("Segoe UI Semibold", 0, 13)); // NOI18N
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cancelBtn, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(submitBtn, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(printReceiptBtn))
                        .addComponent(transactPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(titleLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transactPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(printReceiptBtn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitBtn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Action performed when the "Print Receipt" button is clicked.
     * Constructs and displays a receipt based on transaction data.
     *
     * @param evt Action event triggered by the button click
     */
    private void printReceiptBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_printReceiptBtnActionPerformed
        // Instantiate ReceiptInvoiceGUI
        ReceiptInvoiceGUI receipt = new ReceiptInvoiceGUI();
        
        // Format and set content to be displayed on the receipt
        StringBuilder content = new StringBuilder();
        for (TransactionHandling item : transactionList) {
            // Get the item name and ensure it's limited to 14 characters and without leading/trailing spaces
            String itemName = item.getName().trim().replace(" ", "");
            itemName = itemName.length() > 14 ? itemName.substring(0, 14) : itemName;

            // Format each item: name (limited to 14 characters, without spaces), quantity, and price
            String formattedItem = String.format("%-35s\t     %-10s\t                  %-10s\n",
                                                 itemName, item.getQuantity(),
                                                 String.format("₱%.2f", item.getPrice() * item.getQuantity()));
            content.append(formattedItem);
        }
        // Set the receipt list content
        receipt.setReceiptList(content.toString());
        
        // Get the cash amount from the input field
        double cashAmount = Double.parseDouble(paymentAmountTxtField.getText());
        
        // Set the cash amount in the receipt
        receipt.setCashAmount(cashAmount);
        
        // Calculate VATable Sales
        double vatableSales = totalPurchase / 1.12;
        // Set VATable Sales in the receipt
        receipt.setVATableSalesLabel(vatableSales);
        
        // Pass the VAT amount to ReceiptGUI
        receipt.setVATAmount(vatableSales); 

        // Calculate the change
        double change = cashAmount - (vatableSales + vatableSales * 0.12);
        // Display the change in the receipt
        receipt.setChangeAmount(change);
        
        // Get the date of the transaction
        String dateOfTransaction = dateTxtField.getText();
        // Set the date of the transaction in the receipt
        receipt.setDateOfTransaction(dateOfTransaction);
        
        // Generate and Set Receipt ID
        String generatedReceiptID = receiptID.generateReceiptID();
        receipt.setReceiptID(generatedReceiptID);
       
        // Display the receipt
        receipt.setVisible(true);
        receipt.setLocationRelativeTo(null);
        receipt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        // Export the frame as an image using FrameExporter
        FrameExporter.exportFrameAsImage(receipt, generatedReceiptID);
    }//GEN-LAST:event_printReceiptBtnActionPerformed
    
    /**
     * ActionListener method triggered when the 'Cancel' button is clicked in the GUI.
     *
     * @param evt The ActionEvent captured from the GUI.
     */
    private void cancelBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        dispose(); // Close the current window (the frame)
    }//GEN-LAST:event_cancelBtnActionPerformed
    
    /**
     * Action performed when the "Submit" button is clicked.
     * Handles the transaction submission and quantity adjustments.
     *
     * @param evt Action event triggered by the button click
     */
    private void submitBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // Check if the transaction list is empty
        if(transactionList.isEmpty()){
            JOptionPane.showMessageDialog(null, "Transaction is Empty!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
// Check if payment amount is provided
        if (!paymentAmountTxtField.getText().trim().isEmpty()) {
            String customerMoneyStr = paymentAmountTxtField.getText().trim();
            String totalPurchaseStr = totalAmountTxtField.getText().trim();
            
            // Validate customer money and total purchase inputs
            if (isDataValid.isDouble(customerMoneyStr) && isDataValid.isDouble(totalPurchaseStr)) {
                customerMoney = Double.parseDouble(customerMoneyStr);
                totalPurchase = Double.parseDouble(totalPurchaseStr);
                
                // Check if customer's payment is sufficient
                if (customerMoney >= totalPurchase) {
                    // Confirm transaction submission
                    int confirm = JOptionPane.showConfirmDialog(null, "Do you wish to submit transaction?", "Submit", JOptionPane.YES_NO_OPTION);
                    
                    if (confirm == JOptionPane.YES_OPTION) {
                        // Decrease the quantity of purchased items in the data
                        DataHandling dataHandling = new DataHandling(path);
                        dataHandling.decreaseQuantity(list, transactionList, tableData);
                        
                        // Disable further actions and enable printing the receipt
                        addBtn.setEnabled(false);
                        submitBtn.setEnabled(false);
                        paymentAmountTxtField.setEnabled(false);
                        verifyBtn.setEnabled(false);
                        clearBtn.setEnabled(false);
                        prodIDTxtField.setEnabled(false);
                        quantityPicker.setEnabled(false);
                        printReceiptBtn.setEnabled(true);
                        cancelBtn.setText("EXIT");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Input sufficient payment amount!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid amount.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "There is no input. Input payment amount!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitBtnActionPerformed
    
    /**
     * Action performed when the "Clear" button is clicked.
     * Resets the transaction and clears input fields.
     *
     * @param evt Action event triggered by the button click
     */  
    private void clearBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // Clear the transaction list and reset the transaction table
        transactionList.clear();
        DefaultTableModel model = (DefaultTableModel) transactionTable.getModel();
        model.setRowCount(0); // Clear all rows in the table
        
        // Reset input fields and text areas
        totalAmountTxtField.setText("");
        prodIDTxtField.setText("");
        itemPriceTxtField.setText("");
        prodNameTxtField.setText("");
        quantityPicker.setValue(0);
        
        // Disable the "Add" button after clearing
        addBtn.setEnabled(false);
    }//GEN-LAST:event_clearBtnActionPerformed
    
    /**
     * Action performed when the "Add" button is clicked.
     * Adds the selected item to the transaction list and updates the preview area.
     *
     * @param evt Action event triggered by the button click
     */
    private void addBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // Checking if quantity is provided
        if((int) quantityPicker.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Input Quantity!", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            // Creating TransactionHandling object with provided details
            TransactionHandling data = new TransactionHandling(
                prodIDTxtField.getText(),
                prodNameTxtField.getText(),
                (int) quantityPicker.getValue(),
                Double.parseDouble(itemPriceTxtField.getText())
            );

            // Adding data to the transaction list
            transactionList.add(data);
            
            // Updating the preview area in the table
            DefaultTableModel model = (DefaultTableModel) transactionTable.getModel();

            // Fetching details from input fields
            String prodName = prodNameTxtField.getText();
            int quantity = (Integer) quantityPicker.getValue();
            double itemPrice = Double.parseDouble(itemPriceTxtField.getText());

            // Calculating total for this item
            double customTotal = itemPrice * quantity;

            // Creating a new row with item details
            Object[] row = new Object[] {prodName, quantity, customTotal};

            // Adding the row to the table model
            model.addRow(row);
            
            // Aligning the table
            new TableAlignmentRenderer(transactionTable);

            // Showing the total amount in the designated field
            totalAmountTxtField.setText(String.valueOf(handling.getTotal(transactionList)));

            // Resetting input fields
            prodIDTxtField.setText("");
            itemPriceTxtField.setText("");
            prodNameTxtField.setText("");
            quantityPicker.setValue(0);

            // Disabling the "Add" button
            addBtn.setEnabled(false);
        }
    }//GEN-LAST:event_addBtnActionPerformed
    
    /**
     * Action performed when the "Verify" button is clicked.
     * Checks if the product exists and displays its details if found.
     *
     * @param evt Action event triggered by the button click
     */
    private void verifyBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_verifyBtnActionPerformed
        // Fetching the product ID from the input field
        String prodIDCheck = prodIDTxtField.getText();
        boolean check = false;
        
        // Looping through the list to find the matching product
        for(GameData element: list){
            if(element.getProductID().equals(prodIDCheck) ){
                // If product exists, display its details
                check = true;
                itemPriceTxtField.setText(Double.toString(element.getPrice()));
                prodNameTxtField.setText(element.getName());
                quantityChecker = element.getQuantity();
                addBtn.setEnabled(true); // Enable the "Add" button for valid product
                break;
            }
        }

        // Set the maximum number of items they can buy based on available quantity
        ((SpinnerNumberModel) quantityPicker.getModel()).setMaximum(quantityChecker);

        // If the product doesn't exist, display an error message
        if(!check){
            JOptionPane.showMessageDialog(null, "Product not found!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_verifyBtnActionPerformed
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton addBtn;
    private JButton cancelBtn;
    private JButton clearBtn;
    private JLabel dateLabel;
    private JTextField dateTxtField;
    private JLabel itemPriceLabel;
    private JTextField itemPriceTxtField;
    private JScrollPane jScrollPane2;
    private JLabel paymentAmountLabel;
    private JTextField paymentAmountTxtField;
    private JButton printReceiptBtn;
    private JLabel prodIDLabel;
    private JTextField prodIDTxtField;
    private JLabel prodNameLabel;
    private JTextField prodNameTxtField;
    private JLabel quantityLabel;
    private JSpinner quantityPicker;
    private JButton submitBtn;
    private JLabel titleLabel;
    private JLabel totalAmountLabel;
    private JTextField totalAmountTxtField;
    private JPanel transactPanel;
    private JTable transactionTable;
    private JButton verifyBtn;
    // End of variables declaration//GEN-END:variables
}